// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: email_tokens.sql

package db

import (
	"context"
)

const getVerifyEmailTokenByID = `-- name: GetVerifyEmailTokenByID :one
SELECT id, user_id, created_at, expires_at
FROM verify_email_tokens
WHERE id = $1
`

func (q *Queries) GetVerifyEmailTokenByID(ctx context.Context, id string) (VerifyEmailToken, error) {
	row := q.db.QueryRow(ctx, getVerifyEmailTokenByID, id)
	var i VerifyEmailToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const removeVerifyEmailTokenByID = `-- name: RemoveVerifyEmailTokenByID :exec
DELETE FROM verify_email_tokens WHERE id = $1
`

func (q *Queries) RemoveVerifyEmailTokenByID(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, removeVerifyEmailTokenByID, id)
	return err
}
