name: Deploy Preview
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Test Backend"]
    types:
      - completed
    branches: ['main']
    paths:
      - 'backend/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend
    steps:
      - name: Deploy to Preview Server
        uses: appleboy/ssh-action@v1.0.3
        env:
          MICONFIG: ${{ secrets.MICONFIG_PREVIEW }}
          PK: ${{ secrets.BENTO_PK_PREVIEW }}
        with:
          host: ${{ secrets.PREVIEW_SERVER_IP }}
          username: ${{ secrets.PREVIEW_USER }}
          key: ${{ secrets.PREVIEW_SERVER_SSH_KEY }}
          envs: MICONFIG,PK
          script: |
            clean_up() {
              echo "Performing cleanup..."
              cd ~
              echo "Remove repository"
              rm -rf repo
              echo "Docker cleanup"
              docker system prune -f
              echo "Done: Cleanup"
            }
            handle_error() {
              clean_up
              echo "Failed to deploy preview"
              exit 1
            }
            trap 'handle_error' ERR
            echo "Cloning repository"
            cd ~
            rm -rf repo
            git clone git@github.com:${{ github.repository }}.git repo
            cd repo
            cd backend
            echo "Copy deploy preview script"
            cp ../.github/scripts/deploy-preview.sh .
            echo "Running deploy-preview.sh"
            chmod +x deploy-preview.sh
            ./deploy-preview.sh
            clean_up
