name: Build and Deploy Preview / Frontend
on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install pnpm globally
        run: npm install -g pnpm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        working-directory: frontend
        run: pnpm install
      - name: Build
        working-directory: frontend
        run: pnpm build
      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PREVIEW_SERVER_IP }}
          username: ${{ secrets.PREVIEW_USER }}
          key: ${{ secrets.PREVIEW_SERVER_SSH_KEY }}
          source: "frontend/dist/"
          target: "${{ secrets.TARGET_DIR }}"
          strip_components: 2